# **tools used in eda **
experiment 8
# kushal warade

In [24]:
import numpy as np

a = np.array([10,20,30,40])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)


[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [4]:
# dimensions

print(a.ndim)
print(b.ndim)

1
2


In [5]:

print(a.shape)
print(b.shape)

(4,)
(2, 3)


In [7]:

print(a.dtype)
print(b.dtype)


int64
int64


In [8]:

print(np.zeros((2,3)))


[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:

print(np.ones((4,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:

print(np.eye((3)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:

print(np.arange(1,10,2))


[1 3 5 7 9]


In [16]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [17]:

c=a*2
d=a+5
print(c)
print(d)

[20 40 60 80]
[15 25 35 45]


In [18]:
print(np.mean(a))

25.0


In [19]:

print(np.mean(a))


25.0


In [21]:

print(np.max(a))

40


In [22]:
print(np.max(b))

6


In [23]:
print(np.sum(a))


100
